# Generated by Django 4.1.2 on 2022-11-07 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appbank', '0002_cliente_produtos_alter_empleado_apellido_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Productos',
        ),
    ]
